#+title: Books
#+author: OPSXCQ
#+date: 2020-01-01
#+hugo_base_dir: ../../
#+hugo_section: posts
#+hugo_tags[]: study, books, machine learning

Bellow a curated list of books which I consumed in the recent past years, which
my thoughts on them.

* Machine Learning and Data Science books

** TensorFlow for deep learning : from linear regression to reinforcement learning ([[cite:&BharathRamsundar600]])
Overall is a subpar /hello world/ kind of book for =Tensorflow=, nothing but the
basics. Chapter 8 on /Reinforcement Learning/ has some nice examples which are
easy to be understood.

** Hands-On Neural Networks with TensorFlow 2.0: Understand TensorFlow, from static graph to eager execution, and design neural networks ([[cite:&PaoloGaleone674]])
Is a book from /Packt/ but besides the bad reputation from this publisher, the
books is quite good, it touches some more practical subjects, as how to convert
a model to =Tensorflow.js= and some practical examples of using /Generative
Adversarial Networks/. Besides other /Packt/ books where chapters usually don't
maintain a context or narrative in between them, this book focus solely on image
related problems.

* Security

** Bug Bounty Hunting Essentials : Quick-paced guide to help white-hat hackers get through bug bounty programs ([[cite:&CarlosA.Lozano817]])
Chapter on /Basics of Bug Bounty Hunting/ can be skipped, just generic information
which you could do better by reading the official information of the platform of
your choice. The chapter /How to Write a Bug Bounty Report/ lacks real content and
better examples.

The only interesting point about the book starts on the chapters dedicated to
specific vulnerabilities, in which are discussed in details some vulnerabilities
found on famous services, like /Uber, Shopify, Binary.com/ among others.



* References

bibliography:../../library.bib,../../references.bib

* Notes
