kernel:
  image: nuald/kernel:4.12.14-extra
  cmdline: "console=tty0 root=/dev/sdb1 rootwait vga=791"
init:
  - linuxkit/init:6eb0158059b056a1567236280880cb87f03ff008
  - linuxkit/runc:6cf26a0403376de3b5396cb676b88eea4f37aff8
  - linuxkit/containerd:d955db7cd28dbd7be8a17d7063cc6b7f1bf91f0a
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: rngd1
    image: linuxkit/rngd:v0.6
    command: ["/sbin/rngd", "-1"]
  - name: ram-disk
    image: linuxkit/mount:v0.6-amd64
    command: ["mount", ]
  - name: usb-storage
    image: linuxkit/modprobe:v0.6-amd64
    command: ["modprobe", "usb_storage"]
services:
  - name: getty
    image: linuxkit/getty:v0.6
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
  - name: sshd
    image: linuxkit/sshd:v0.6
  - name: monero-miner 
    image: strm/xmrig
    command: ["/bin/xmrig", "-a", "cryptonight", "-o", "stratum+tcp://104.140.201.42:5555", "-p", "Miner01-Kit", "-k", "--donate-level=1", "--cpu-priority", "0", "-u", "YOUR_ADDRESS_HERE"]
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit
